// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weyiwjaophohxzamiorx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleWl3amFvcGhvaHh6YW1pb3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzY5NzcsImV4cCI6MjA2NDExMjk3N30.Sh0w_i_0Bfs2HPMkrs4Dkl4GSG5k8eaOs3gp67uTRgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);